### ISSUE TITLE
Wheel not properly initialized when getInstance is run?

### ISSUE THREAD

**Issue by natejank** [Team2168/2020_SwerveBot#40]
```
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ Unhandled exception: java.lang.NullPointerException ﻿﻿ org.team2168.thirdcoast.swerve.Wheel.set(Wheel.java:105) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ Error at org.team2168.thirdcoast.swerve.Wheel.set(Wheel.java:105): Unhandled exception: java.lang.NullPointerException ﻿
﻿﻿﻿﻿﻿﻿ 	at org.team2168.thirdcoast.swerve.Wheel.set(Wheel.java:105) ﻿
﻿﻿﻿﻿﻿﻿ 	at org.team2168.thirdcoast.swerve.SwerveDrive.drive(SwerveDrive.java:165) ﻿
﻿﻿﻿﻿﻿﻿ 	at org.team2168.subsystem.Drivetrain.drive(Drivetrain.java:141) ﻿
﻿﻿﻿﻿﻿﻿ 	at org.team2168.commands.drivetrain.DriveWithJoystick.execute(DriveWithJoystick.java:41) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.command.Command.run(Command.java:296) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.command.Scheduler.run(Scheduler.java:238) ﻿
﻿﻿﻿﻿﻿﻿ 	at org.team2168.Robot.disabledPeriodic(Robot.java:157) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.IterativeRobotBase.loopFunc(IterativeRobotBase.java:239) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:86) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:276) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:348) ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 1 ﻿﻿ Loop time of 0.02s overrun
 ﻿﻿ edu.wpi.first.wpilibj.IterativeRobotBase.printLoopOverrunMessage(IterativeRobotBase.java:309) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ 	at org.team2168.Main.main(Main.java:27) ﻿
﻿﻿﻿﻿﻿﻿  ﻿
﻿﻿﻿﻿﻿﻿ Watchdog not fed within 0.020000s ﻿
﻿﻿﻿﻿﻿﻿ ﻿Warning﻿ at edu.wpi.first.wpilibj.IterativeRobotBase.printLoopOverrunMessage(IterativeRobotBase.java:309): Loop time of 0.02s overrun ﻿
﻿﻿﻿﻿﻿﻿  ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 1 ﻿﻿ Robots should not quit, but yours did! ﻿﻿ edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:291) ﻿﻿﻿
```

**Comment by jcorcoran** [comment]
OBE
